# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='average_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='calories',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elapsed_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elev_high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elev_low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_watts',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='moving_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='photos',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date_local',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='total_elevation_gain',
            field=models.FloatField(),
        ),
    ]
