# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20160402_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='elev_high',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='elev_low',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='max_watts',
        ),
    ]
