# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-08 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20160403_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='access_token',
            field=models.CharField(default='12363c99d46a329f5e810e3fb7135bc45caaa7c7', max_length=45),
            preserve_default=False,
        ),
    ]
