# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20160410_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
