# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20160413_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_type',
            fields=[
                ('type', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('elevation', models.FloatField()),
                ('distance', models.FloatField()),
            ],
        ),
    ]
