# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity_type',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity_type',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity_type',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
