# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='picture',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='photos',
        ),
        migrations.AddField(
            model_name='picture',
            name='activity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.activity'),
        ),
    ]
