# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20160424_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='name',
            field=models.CharField(default='Tesla', max_length=140),
            preserve_default=False,
        ),
    ]
