# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='rank_delta',
            field=models.IntegerField(default=0),
        ),
    ]
